// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chirps.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteAllChirps = `-- name: DeleteAllChirps :exec
DELETE FROM chirps
`

func (q *Queries) DeleteAllChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChirps)
	return err
}

const deleteChirpByID = `-- name: DeleteChirpByID :one
DELETE FROM chirps
WHERE id = $1
RETURNING id, created_at, updated_at, body, user_id
`

func (q *Queries) DeleteChirpByID(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, deleteChirpByID, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getChirpByID = `-- name: GetChirpByID :one
SELECT id, body, updated_at, created_at, user_id
FROM chirps
WHERE id = $1
`

type GetChirpByIDRow struct {
	ID        uuid.UUID
	Body      string
	UpdatedAt time.Time
	CreatedAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) GetChirpByID(ctx context.Context, id uuid.UUID) (GetChirpByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChirpByID, id)
	var i GetChirpByIDRow
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getChirps = `-- name: GetChirps :many
SELECT id, body, updated_at, created_at, user_id
FROM chirps
ORDER BY id
`

type GetChirpsRow struct {
	ID        uuid.UUID
	Body      string
	UpdatedAt time.Time
	CreatedAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) GetChirps(ctx context.Context) ([]GetChirpsRow, error) {
	rows, err := q.db.QueryContext(ctx, getChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChirpsRow
	for rows.Next() {
		var i GetChirpsRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChirp = `-- name: UpdateChirp :one
UPDATE chirps SET (updated_at, body) = (NOW(), $1)
WHERE id = $2
RETURNING id, created_at, updated_at, body, user_id
`

type UpdateChirpParams struct {
	Body string
	ID   uuid.UUID
}

func (q *Queries) UpdateChirp(ctx context.Context, arg UpdateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, updateChirp, arg.Body, arg.ID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
